# Generated by Django 4.1.3 on 2023-01-30 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.PositiveIntegerField()),
                ('pid', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.PositiveIntegerField()),
                ('subscribed_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_p', to='distqueue.topic')),
            ],
        ),
        migrations.CreateModel(
            name='LogMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod', to='distqueue.producer')),
                ('topic_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_name_lm', to='distqueue.topic')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ConsumerViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cv', to='distqueue.consumer')),
                ('viewed_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_log', to='distqueue.logmessage')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumerSubscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_topic', to='distqueue.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cs', to='distqueue.consumer')),
            ],
        ),
        migrations.AddField(
            model_name='consumer',
            name='subscriptions',
            field=models.ManyToManyField(through='distqueue.ConsumerSubscriptions', to='distqueue.topic'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='views',
            field=models.ManyToManyField(through='distqueue.ConsumerViews', to='distqueue.logmessage'),
        ),
    ]
