# Generated by Django 4.1.3 on 2023-01-30 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distqueue', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ids',
        ),
    ]
