# Generated by Django 4.1.7 on 2023-03-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distqueue', '0003_topic_partition_number_alter_logmessage_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='subscriptions',
        ),
        migrations.RemoveField(
            model_name='logmessage',
            name='prod',
        ),
        migrations.AddField(
            model_name='consumer',
            name='subscription',
            field=models.ManyToManyField(through='distqueue.ConsumerSubscriptions', to='distqueue.topic'),
        ),
    ]
